version: '3'

services:
  app:
    build: .
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=graphql_api
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=graphql_api
